"""Change the income_date attribute of DateTime a Date

Revision ID: 0bc82238599b
Revises: d09889116f0d
Create Date: 2023-05-16 14:33:27.118486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc82238599b'
down_revision = 'd09889116f0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('income_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('outgoing', schema=None) as batch_op:
        batch_op.alter_column('outgoing_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outgoing', schema=None) as batch_op:
        batch_op.alter_column('outgoing_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('income_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
