"""Delete type_document attribute of the User Model

Revision ID: d09889116f0d
Revises: 
Create Date: 2023-05-15 11:37:53.925623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09889116f0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('type_document')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_document', sa.VARCHAR(length=5), nullable=True))

    # ### end Alembic commands ###
